# Title shown in Application Information tab.
title: Samsung SDS Nexledger Universal
# Sub Title shown in Application Information tab.
description: Enterprise blockchain platform optimized for your business...
schemaVersion: 1.1.0
version: "V2.2"

# URL of Logo Icon used on Application Information tab. Logo must be 130x130 pixels.
# (Optional)
# logoUrl: https://cloudmarketplace.oracle.com/marketplace/content?contentId=53066708

# Used in Application Information tab to Hyperlink Title and Logo to the Marketplace
# Listing.
# Also used to link to Listing Usage section for "View Instructions".
# (Optional) If it is missing, Application Information uses the
# "marketplace-listing-id" tag for the same purpose.
#source:
#  type: marketplace
#  reference: 16132843


locale: "en"
variableGroups:
  - title: "Default Variable Group"
    # visible: true
    variables:
      - tenancy_ocid
      - region
      - compartment_ocid
      - user_ocid
#      - api_fingerprint
#      - api_private_key_path
      - mp_subscription_enabled
      - mp_listing_id
      - mp_listing_resource_id
      - mp_listing_resource_version

  - title: "Nexledger Configuration"
    variables:
      - nexledger_engine

  - title: "Compute Configuration"
    variables:
      - instance_display_name
      - vm_image_id # ?
      - vm_shape
      - vm_timezone
      - availability_domains
      - boot_volume_size_in_gbs
      - ssh_public_key

  - title: "Network Configuration"
    variables:
      - network_strategy
      - network_configuration_strategy
      - vcn_id
      - vcn_cidr
      - vcn_dns_label
      - vcn_name
      - subnet_id

  - title: "Enum Configuration"
    variables:
      - network_strategy_enum

  - title: "Additional Configuration"
    variables:
      - label_prefix
      - tagging

variables:

  ######################################################
  ################   DEFAULT VARIABLES   ###############
  ######################################################

  tenancy_ocid:
    type: string
    title: Tenancy ID
    description: The Oracle Cloud Identifier (OCID) for your tenancy
    required: true

  region:
    type: oci:identity:region:name
    title: Region
    description: The region in which to create all resources
    required: true

  compartment_ocid:
    type: oci:identity:compartment:id
    required: true
    title: Compartment
    description: The compartment in which to create all resources for Nexledger
    default: compartment_ocid

  user_ocid:
    type: oci:identity:user:userid
    required: true
    title: User ID
    description: ID of user that terraform will use to create the resources

  ######################################################
  ##############   MARKETPLACE VARIABLES   #############
  ######################################################

  mp_listing_id:
    type: string
    required: true
    description: Marketplace Listing ID

  mp_listing_resource_id:
    type: oci:core:image:id
    required: true
    description: Marketplace Image OCID
    dependsOn:
      compartmentId: compartment_ocid

  mp_listing_resource_version:
    type: string
    required: true
    description: Marketplace Listing package version

  mp_subscription_enabled:
    type: boolean
    title: Use Marketplace Image?
    default: false


  ######################################################
  ###############   NEXLEDGER VARIABLES   ##############
  ######################################################

  nexledger_engine:
    type: string
    title: Type of Nexledger Blockchain backend to run (N,H,E)
    required: true
    default: N

  ######################################################
  ##############    COMPUTE VARIABLES      #############
  ######################################################

  instance_display_name:
    type: string
    required: true
    title: Instance Name
    description: The name of the VM Instance
    default: nexledger_instance

  vm_image_id:
    type: string
    required: true
    title: Custom Image OCID
    # visible:
    #   eq:
    #     - mp_subscription_enabled
    #     - false

  vm_shape:
    type: oci:core:instanceshape:name
    default: VM.Standard2.2
    title: Compute Shape
    required: true
    dependsOn:
      compartmentId: compartment_ocid
      imageId: mp_listing_resource_id

  vm_timezone:
    type: string
    default: Asia/Seoul
    title: Timezone to place VM
    required: true

  availability_domains:
    type: oci:identity:availabilitydomain:name
    dependsOn:
      compartmentId: compute_compartment_ocid
    required: true
    default: 1
    title: Availability Domain
    description: Availability Domain

  boot_volume_size_in_gbs:
    type: oci:core:bootvolume:sizeingb
    default: 50
    title: Boot Volume Size for instance
    required: true

  ssh_public_key:
    type: string
    required: true
    title: Public SSH Key string
    description: Public SSH Key to access VM via SSH

  ######################################################
  ##############    NETWORK VARIABLES      #############
  ######################################################

  network_strategy:
    type: enum
    title: Network Strategy
    description: Create or use existing Network Stack (VCN and Subnet)
    enum:
      - "Create New VCN and Subnet"
      - "Use Existing VCN and Subnet"
    required: true
    default: "Create New VCN and Subnet"

  network_configuration_strategy:
    visible: #($network_strategy  == ""Create New VCN and Subnet"")
      eq:
        - network_strategy
        - "Create New VCN and Subnet"
    type: enum
    title: Configuration Strategy
    description: Use recommended configuration or customize it
    enum:
      - "Use Recommended Configuration"
      - "Customize Network Configuration"
    required: true
    default: "Use Recommended Configuration"

  vcn_id:
    visible: #($network_strategy  == "Use Existing VCN and Subnet")
      eq:
        - network_strategy
        - "Use Existing VCN and Subnet"
    type: oci:core:vcn:id
    dependsOn:
      compartmentId: compartment_ocid
    required: true
    title: Existing VCN
    description: An existing Virtual Cloud Network (VCN) in which to create the compute instances, network resources, and load balancers. If not specified, a new VCN is created.

  vcn_cidr_block:
    visible: #($network_strategy  == ""Create New VCN and Subnet"") AND (network_configuration_strategy ==  "Customize Network Configuration")
      and:
        - eq:
            - network_strategy
            - "Create New VCN and Subnet"
        - eq:
            - network_configuration_strategy
            - "Customize Network Configuration"
    type: string
    required: true
    pattern: "^(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9]).(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9]).(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9]).(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9])\\/(3[0-2]|[1-2]?[0-9])$"
    title: CIDR Block
    description: The CIDR of the new Virtual Cloud Network (VCN). If you plan to peer this VCN with another VCN, the VCNs must not have overlapping CIDRs.

  vcn_dns_label:
    visible: #($network_strategy  == ""Create New VCN and Subnet"") AND (network_configuration_strategy ==  "Customize Network Configuration")
      and:
        - eq:
            - network_strategy
            - "Create New VCN and Subnet"
        - eq:
            - network_configuration_strategy
            - "Customize Network Configuration"
    type: string
    required: true
    title: DNS Label
    maxLenght: 15
    description: VCN DNS Label. Only letters and numbers, starting with a letter. 15 characters max.

  vcn_name:
    visible: #($network_strategy  == ""Create New VCN and Subnet"") AND (network_configuration_strategy ==  "Customize Network Configuration")
      and:
        - eq:
            - network_strategy
            - "Create New VCN and Subnet"
        - eq:
            - network_configuration_strategy
            - "Customize Network Configuration"
    type: string
    required: true
    title: Name
    description: The name of the new Virtual Cloud Network (VCN)

  subnet_id:
    visible: #($network_strategy  == "Use Existing VCN and Subnet")
      eq:
        - network_strategy
        - "Use Existing VCN and Subnet"
    type: oci:core:subnet:id
    dependsOn:
      vcnId: vcn_id
      compartmentId: compartment_ocid
    default: ''
    required: true
    title: Existing Subnet
    description: An existing Management subnet. This subnet must already be present in the chosen VCN.

  ######################################################
  ############     Additional VARIABLES      ###########
  ######################################################

  label_prefix:
    type: string
    required: true
    default: nex
    title: Label Prefix
    description: String value that will be prepended to all resources

  tagging:
    type: map
    required: true
    title: Tagging values
    description: Tags for the deployment ( computetag and networktag)


#############################################
###########    OUTPUT GROUPS     ############
#############################################

outputGroups:
  - title: "Compute"
    outputs:
      - private_ip
      - public_ip

  - title: "VCN"
    outputs:
      - vcn_id
      - nat_gateway_id
      - ig_route_id
      - nat_route_id
      - cidr
  - title: "High-Level"
    outputs:
      - ssh_to_admin

#############################################
##############     OUTPUTS     ##############
#############################################

outputs:

  instance_public_ip:
    type: link
    title: Public IP
    visible: true

  instance_private_ip:
    type: link
    title: Private IP
    visible: true

  High-Level_ssh_to_admin:
    type: string
    title: SSH link to Admin
    visible: true