# Title shown in Application Information tab.
title: Samsung SDS Nexledger Universal
# Sub Title shown in Application Information tab.
description: Enterprise blockchain platform optimized for your business...
schemaVersion: 1.1.0
version: "V2.2"

# URL of Logo Icon used on Application Information tab. Logo must be 130x130 pixels.
# (Optional)
# logoUrl: https://cloudmarketplace.oracle.com/marketplace/content?contentId=53066708

# Used in Application Information tab to Hyperlink Title and Logo to the Marketplace
# Listing.
# Also used to link to Listing Usage section for "View Instructions".
# (Optional) If it is missing, Application Information uses the
# "marketplace-listing-id" tag for the same purpose.
#source:
#  type: marketplace
#  reference: 16132843


locale: "en"
variableGroups:
  - title: "Default Variable Group"
    # visible: true
    variables:
      - tenancy_ocid
      - region
      - compartment_ocid
      - user_ocid
#      - api_fingerprint
#      - api_private_key_path
      - mp_subscription_enabled
      - mp_listing_id
      - mp_listing_resource_id
      - mp_listing_resource_version

  - title: "Nexledger Configuration"
    variables:
      - nexledger_engine

  - title: "Compute Configuration"
    variables:
      - instance_display_name
      - vm_image_id # ?
      - vm_shape
      - vm_timezone
      - availability_domains
      - boot_volume_size_in_gbs
      - ssh_public_key

  - title: "Network Configuration"
    variables:
      - network_strategy
      - vcn_id
      - nat_gateway_enabled
      - vcn_cidr
      - vcn_dns_label
      - vcn_name
      - subnet_id


  - title: "Additional Configuration"
    variables:
      - label_prefix
      - tagging

variables:

  ######################################################
  ################   DEFAULT VARIABLES   ###############
  ######################################################

  tenancy_ocid:
    type: string
    title: Tenancy ID
    description: The Oracle Cloud Identifier (OCID) for your tenancy
    required: true

  region:
    type: oci:identity:region:name
    title: Region
    description: The region in which to create all resources
    required: true

  compartment_ocid:
    type: oci:identity:compartment:id
    required: true
    title: Compartment
    description: The compartment in which to create all resources for Nexledger
    default: compartment_ocid


  ######################################################
  ##############   MARKETPLACE VARIABLES   #############
  ######################################################

  mp_listing_id:
    type: string
    required: true
    description: Marketplace Listing ID

  mp_listing_resource_id:
    type: oci:core:image:id
    required: true
    description: Marketplace Image OCID
    dependsOn:
      compartmentId: compartment_ocid

  mp_listing_resource_version:
    type: string
    required: true
    description: Marketplace Listing package version

  mp_subscription_enabled:
    type: boolean
    title: Use Marketplace Image?
    default: false


  ######################################################
  ###############   NEXLEDGER VARIABLES   ##############
  ######################################################

  nexledger_engine:
    type: string
    title: Type of Nexledger Blockchain backend to run (N,H,E)
    required: true
    default: N

  ######################################################
  ##############    COMPUTE VARIABLES      #############
  ######################################################

  instance_display_name:
    type: string
    required: true
    title: Instance Name
    description: The name of the VM Instance
    default: nexledger_instance

  vm_image_id:
    type: string
    required: true
    title: Custom Image OCID
    # visible:
    #   eq:
    #     - mp_subscription_enabled
    #     - false

  vm_shape:
    type: oci:core:instanceshape:name
    default: VM.Standard2.2
    title: Compute Shape
    required: true
    dependsOn:
      compartmentId: compartment_ocid
      imageId: mp_listing_resource_id

  vm_timezone:
    type: string
    default: Asia/Seoul
    title: Timezone to place VM
    required: true

  availability_domains:
    type: oci:identity:availabilitydomain:name
    dependsOn:
      compartmentId: compute_compartment_ocid
    required: true
    default: 1
    title: Availability Domain
    description: Availability Domain

  boot_volume_size_in_gbs:
    type: oci:core:bootvolume:sizeingb
    default: 50
    title: Boot Volume Size for instance
    required: true

  ssh_public_key:
    type: string
    required: true
    title: Public SSH Key string
    description: Public SSH Key to access VM via SSH


